import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { useState } from 'react';
import './globals.css'
import { NavBar } from '@/components/NavBar'
import { Footer } from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-zinc-900 to-gray-900 text-font-primary`}>
        <NavBar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
